version: "3.8"

services:
  # image project
  minimal-project-app:
    container_name: minimal-project-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user=jenkins
        - uid=132
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - minimal-project

  # nginx
  minimal-project-nginx:
    container_name: minimal-project-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "4000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - minimal-project

networks:
  minimal-project:
    name: minimal-project
